### ISSUE TITLE
failed assertion at PgNoticeMessagesPlugin: "processNotice should not be set yet!"

### ISSUE THREAD

**Issue by RichardForrester** [graphile/operation-hooks#28] opened 2021-10-17 07:16 UTC
### Summary

I have come across an assertion error message when using operation-hooks in combination with a different plugin "postgraphile-plugin-many-create-update-delete" (hereafter "mn-plugin"). Both plugins appear to be working perfectly when not used together and the error is thrown when attempting to make a mutation pursuant to the mn-plugin; however the error is thrown by an assertion of the operation-hook plugin. Also, if I comment out the assertion located at line 39 of the source file "PgNoticeMessagesPlugin" that appears to resolve the conflict; however, I do not know enough about the plugin system to understand the basis for the assertion. 

### Steps to reproduce

```json
  "dependencies": {
    "@graphile/operation-hooks": "^1.0.0",
    "postgraphile-plugin-many-create-update-delete": "^1.0.6"
  },
```
After standard pg-library setup, preform a mn-plugin mutation:

```graphql
mutation {
  mnCreateIndividual(
    input: {
      mnIndividual: [
        { first: "John", last: "Doe" }
        { first: "Jane", last: "Doe" }
      ]
    }
  ) {
    query {
      individuals {
        nodes {
          first
          last
        }
      }
    }
  }
}

```

### Expected results

This is the correct result that I get when commenting out the assertion located at line 39 of the source file "PgNoticeMessagesPlugin":

```json
{
  "data": {
    "mnCreateIndividual": {
      "query": {
        "individuals": {
          "nodes": [
            {
              "first": "John",
              "last": "Doe"
            },
            {
              "first": "Jane",
              "last": "Doe"
            }
          ]
        }
      }
    }
  },
  "explain": [
    {
      "query": "with __local_0__ as (\n          INSERT INTO \"public\".\"individuals\" \n          (\"individual_id\", \"tenant_id\", \"first\", \"last\", \"prefix\", \"middle\", \"gender\", \"suffix\", \"ssn\", \"birth\", \"death\")\n            VALUES (default, default, $1, $2, default, default, default, default, default, default, default),(default, default, $3, $4, default, default, default, default, default, default, default) returning *) select ((case when __local_0__ is null then null else __local_0__ end))::text from __local_0__",
      "plan": "CTE Scan on __local_0__  (cost=0.03..0.08 rows=2 width=32)\n  CTE __local_0__\n    ->  Insert on individuals  (cost=0.00..0.03 rows=2 width=1480)\n          ->  Values Scan on \"*VALUES*\"  (cost=0.00..0.03 rows=2 width=1480)"
    },
    {
      "query": "with __local_0__ as (select (str::\"public\".\"individuals\").*\nfrom unnest(($1)::text[]) str) select to_json(__local_0__.\"individual_id\") as \"@ophookpk__individual_id\"\nfrom __local_0__ as __local_0__\n\nwhere (TRUE) and (TRUE)\n\n\n",
      "plan": "Function Scan on unnest str  (cost=0.00..0.04 rows=2 width=32)"
    },
    {
      "query": "with __local_0__ as (select to_json((json_build_object('__identifiers'::text, json_build_array(__local_1__.\"individual_id\"), 'first'::text, (__local_1__.\"first\"), 'last'::text, (__local_1__.\"last\")))) as \"@nodes\" from (select __local_1__.*\nfrom \"public\".\"individuals\" as __local_1__\n\nwhere (TRUE) and (TRUE)\norder by __local_1__.\"individual_id\" ASC\n\n) __local_1__), __local_2__ as (select json_agg(to_json(__local_0__)) as data from __local_0__) select coalesce((select __local_2__.data from __local_2__), '[]'::json) as \"data\" ",
      "plan": "Result  (cost=13.18..13.19 rows=1 width=32)\n  InitPlan 1 (returns $0)\n    ->  Aggregate  (cost=13.16..13.17 rows=1 width=32)\n          ->  Sort  (cost=11.91..12.04 rows=50 width=1480)\n                Sort Key: __local_1__.individual_id\n                ->  Seq Scan on individuals __local_1__  (cost=0.00..10.50 rows=50 width=1480)"
    }
  ]
}
```
### Actual results

The exact error message as it appears in graphiql is:

```json 
{
  "errors": [
    {
      "errcode": "ERR_ASSERTION",
      "extensions": {
        "messages": [],
        "exception": {
          "errcode": "ERR_ASSERTION"
        }
      },
      "message": "processNotice should not be set yet!",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "mnCreateIndividual"
      ],
      "stack": [
        "AssertionError [ERR_ASSERTION]: processNotice should not be set yet!",
        "    at registerNotifyListener (/Users/richard/repos/yp-postgraphile/node_modules/@graphile/operation-hooks/lib/PgNoticeMessagesPlugin.js:39:17)",
        "    at applyHooks (/Users/richard/repos/yp-postgraphile/node_modules/@graphile/operation-hooks/lib/OperationHooksCorePlugin.js:9:28)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)",
        "    at async resolve (/Users/richard/repos/yp-postgraphile/node_modules/@graphile/operation-hooks/lib/OperationHooksCorePlugin.js:116:38)",
        "    at async resolve (/Users/richard/repos/yp-postgraphile/node_modules/@graphile/operation-hooks/lib/OperationHooksCorePlugin.js:122:32)",
        "    at async /Users/richard/repos/yp-postgraphile/node_modules/postgraphile/build/postgraphile/withPostGraphileContext.js:165:24",
        "    at async withAuthenticatedPgClient (/Users/richard/repos/yp-postgraphile/node_modules/postgraphile/build/postgraphile/withPostGraphileContext.js:105:24)",
        "    at async /Users/richard/repos/yp-postgraphile/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:708:34",
        "    at async Promise.all (index 0)",
        "    at async graphqlRouteHandler (/Users/richard/repos/yp-postgraphile/node_modules/postgraphile/build/postgraphile/http/createPostGraphileHttpRequestHandler.js:640:23)"
      ]
    }
  ],
  "data": {
    "mnCreateIndividual": null
  },
  "explain": []
}
```

### Additional context

I don't believe my setup is relevant, but here it is:

    macOS 11.6
    node v14.17.6 
    "postgraphile": "^4.12.3"

### Possible Solution

Someone who understands the purpose of the assertion should evaluate why this other plugin is causing a failure and then decide whether the test should be changed, or if one of the plugins has an issue that needs to be addressed.

**Comment by benjie** [comment] 2021-10-18 09:28
The reason for the assertion is that on the line following the assertion the processNotice property is installed:

https://github.com/graphile/operation-hooks/blob/7623823feb019195c2f16d47643a688a106aaed4/src/PgNoticeMessagesPlugin.ts#L51-L55

If it's already there then it indicates one of many potential situations:

1. `registerNotifyListener` has been called more than once in the current operations
2. the `processNotice` has not been cleaned up from a previous operation (should be cleaned up in `unregisterNotifyListener`)
3. Something else has added `processNotice` to the client.

My guess is that `postgraphile-plugin-many-create-update-delete` calls the resolver multiple times leading to this operation hook being called multiple times unexpectedly, resulting in the error. This is not a bug in @graphile/operation-hooks from what I can tell so I am closing this issue - consider raising an issue against the `postgraphile-plugin-many-create-update-delete` plugin.

**Closed as completed by benjie** 2021-10-18 09:28 UTC
